### ISSUE TITLE
Documentation for Components

### ISSUE THREAD

**Issue by NehemiahK** [NehemiahK/Another-React-Lib#26]
Some components have been added in without documentation. Would be awesome if we could add documentation for those missing

**Comment by raghubandaru** [comment]
Adding PropTypes in the Component files?

**Comment by NehemiahK** [comment]
I meant that some components have been added in src already, but there is no example and prop types in the docs

**Comment by jessekoester** [comment]
Can I take a crack at this?

**Comment by edgarberlinck** [comment]
I think that would be better if whe automate this using jsdocs or something like that.

**Comment by NehemiahK** [comment]
@edgarberlinck could you elaborate on that solution. Sounds interesting

**Comment by edgarberlinck** [comment]
Sure. Will can handle it.

At this time, if someone want to manually add docs would be great.

**Comment by alexyiangou** [comment]
Hey there I would like to add my touch on this :slightly_smiling_face: : I actually got something ready, I just dont have push rights for some reason..

**Comment by edgarberlinck** [comment]
You should fork this repo in order to push your work there.  After your
work is done you should open a Pull Request. Remember to attach it to an
open issue in order to qualify it to hacktoberfest. Just use #<Issue
number> at your pull resquest or commit messages.

Em sex, 4 de out de 2019 às 04:54, Alexandros Yiangou <
notifications@github.com> escreveu:
